### ISSUE TITLE
Building and publishing project docs

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#148]
As the project continues to improve its documentation (ex. high-level project information in addition to API docs), it would be helpful to automatically publish updates to GitHub pages (or elsewhere).  I've started this process on the [`ghp/docs`](https://github.com/ml4ai/skema/tree/ghp/docs) branch, but haven't succeeded in building the static site locally using the provided instructions.  

### Build errors
My main development machine is an M1 mac (aarch64/arm64) which is likely a big part of the issues I encountered.  I first ran into bus errors.  After moving to newer versions of Haskell and its build tools compatible with the M1, those errors went away.  My latest set of errors were complaints around the transitive dependencies of Hakyll and Pandoc missing from `stack.yaml`. Admittedly, I'm not very familiar with the Haskell ecosystem...  

### Proposal
Moving forward, it would be helpful to have a (multiarch) docker image that we can use to build the static site.

**Comment by adarshp** [comment]
@myedibleenso - The current docs at https://skema.sista.arizona.edu were generated by me and manually rsynced onto kraken for deployment. I see now that there is a bug in `generator.hs` - probably what happened is that I made a change and forgot to commit it. I'll push a bugfix, but I also agree that there should be a docker image for the static site.

But I'll also say that I'm not wedded to using Haskell for this purpose, it was simply the quickest option for me since that's what I use for my personal site (https://adarsh.cc). If you have a better solution and the time to implement it, that is totally ok with me.

**Comment by myedibleenso** [comment]
Thanks, @adarshp , for the prompt response!  

I had to make several other changes to get things to work on my end (ex. remove LLVM from my path, switch to a different ghc version, etc), but I've managed to build things successfully on my M1.  I'll open a PR that includes the changes along with a workflow that publishes the site to GitHub Pages whenever changes are merged into `main`.

**Comment by adarshp** [comment]
Great, thanks @myedibleenso !

**Comment by myedibleenso** [comment]
(Sorry.  I should've squashed those commits before opening the PR)

**Comment by adarshp** [comment]
> (Sorry. I should've squashed those commits before opening the PR)

No worries! I've actually set the default merge method for PRs for this repo to 'Squash and merge', so we can let Github take care of that step.
