### ISSUE TITLE
[fortran] Adding front-end support for handling Fortran compiler directives

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#185]
The following Fortran compiler directives are not yet supported:
- `#if`,`#ifdef`,`#elif`,`#else`

- [ ] Write script to identify and translate instances of header (or other file) inclusion that assumes system-context locations
  - [x] translate to be *local* references to included files
  - [ ] collect all local file references and provide as summary output for user to manually collect the needed libraries
  - [ ] Develop convention for how included files will be locally managed/stored
- [x] Add support for using gcc/gfortran pre-compiler to handle all pre-compiler directives
- [x] Develop convention for managing generated post-pre-compiler processing
  - [x] option to generate intermediate products (e.g., pre-processing script that handles line continuations and system-includes); in separate directory for each file; for multi-file system, mirror source directory tree structure; can specify root of generate intermediate products

**Comment by cl4yton** [comment]
After review, here is the required Fortran front-end pipeline logic:
Fortran preprocessing pipeline has these steps:
- Run script to identify and replace system includes with local includes
- Run gcc C-pre-processor – this processes all compiler directive, output is new source code with no compiler directives (including NO includes)
- Run this script after C-pre-processor (since C-pre-processor could have introduce new line-continuations and/or unsupported idioms):
  - fix line-continuations
  - identify any unsupported idioms
- Send updated source to tree-sitter.

**Comment by myedibleenso** [comment]
@vincentraymond-ua , will this be the same PR as #194 ?
