### ISSUE TITLE
[python] Support for closures (nested fn definition)

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#190]
- [x] Change function visitation order in Python -> CAST generation
- [x] GroMeT support for closures (ensure we're calling the right function)
- [ ] Add test that asserts correct function is referenced

**Comment by myedibleenso** [comment]
Status update as of 5/23

- broad strokes complete; now cleaning things up and adding tests ( @titomeister , please be sure to add multiple unit tests as part of your PR)

**Comment by titomeister** [comment]
Update for 5/30

- Fixed an issue that involved variable name clashes. When a nested function has the same name as a variable or argument from an outer function definition, we get a name clash because it's ambiguous as to what name can be picked. 
- The name clash we can resolve by treating any incoming locals and arguments from a previous outer scope as OPIs to the inner FN box. These OPIs are copies of what's in the outer scope, so as to prevent loss of information. Then, if a local or variable in the inner function definition clashes with something that is in an outer scope, then it can overwrite the OPI without worrying about losing any actual information.

**Comment by myedibleenso** [comment]
Update for 6/2

- Wiring appears to be correct
- Just need unit tests

**Comment by titomeister** [comment]
Update 6/6
 - The Bucky full model has an issue generating GroMEt that was detected as part of double checking ingestion with models.
 - In particular, a bug has been introduced when two variables that live in two different functions, but have the same name (i.e. x in foo() and x in bar()), have the same ID. That is x has ID 0 in foo() and x also has ID 0 in bar(). This is incorrect behavior as these should have different, unique IDs. This causes an issue when it goes to generating Annotated CAST which prevents GroMEt from being generated.
 - I'm currently working on the fix for this. I know where in the Python to CAST code this is happening.

**Comment by titomeister** [comment]
Update 6/9
- Fixed the issue with the Bucky full model generation.
- Working on unit tests for
   - references to x in same function should have same ID
   - references to x in different functions should have different IDs
