### ISSUE TITLE
[python] Filename truncation in GroMEt generation

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#202]
Some Python files (TODO: name some specific examples), when sent through the pipeline, have their output GroMEt names truncated by a letter or two. Investigate what's causing this.

**Comment by vincentraymond-ua** [comment]
This issue is caused by the system_name calculation in single_file_ingester.py. Specifically, this line:

 `system_name = os.path.basename(path).strip(".py")`

The intention is to have it strip the string ".py" from the end of the filename. However, this is instead stripping any '.', 'p', and 'y' characters from the end of the filename. 

This causes issues with filenames such as steady.py and ready.py (as discovered by Tito)

**Comment by vincentraymond-ua** [comment]
To fix this, we can check if the filename ends in .py using the string.endswith(...) method and then use slicing to remove the suffix.

**Comment by adarshp** [comment]
@vincentraymond-ua  - [Pathlib](https://docs.python.org/3/library/pathlib.html) might be useful here.

**Comment by myedibleenso** [comment]
Update: CI is running again, so PR is incoming (per @vincentraymond-ua )
