### ISSUE TITLE
[TR] Unify TR docker images

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#227]
We have two TR docker images:

1. [One that builds a fat ja](https://github.com/ml4ai/skema/blob/main/skema/text_reading/text_reading/Dockerfile)r and is currently being used by UWisc within COSMOS.
2. Another one that runs the TR api in production mode, defined as [an sbt plug in](https://github.com/ml4ai/skema/blob/main/skema/text_reading/text_reading/webapp/docker.sbt)

Ideally, we should have a single image whose default behavior is 2, but that people can use to run our "apps" from the command line, like COSMOS folks are doing right now.

I am not sure what is the best approach, so I am starting this conversation here.

**Comment by kwalcock** [comment]
I did see this and may be able to look starting this weekend, June 17.

**Comment by kwalcock** [comment]
I looked at this for quite some time and don't think this is a good strategy.  The advantage of a single multi-purpose image over two (or three) single-purpose images seems minimal to me.  It's not how docker is intended to work, it doesn't mesh well with sbt, and changes related to one purpose will force updates to the image used for the other purpose.  I was especially convinced of this after noticing that Python is thrown in there as well.  That's almost reason enough for a third image, IMO.  The Python code is only making up for people passing in the wrong file format (parquet) into AnnotateCosmosJsonFiles so that in housing the conversion programs (annotate_cosmos_json and cosmos_integration.py), the Docker image is just glueing glue together.  I would instead add AnnotateCosmosParquetFiles, remove all the glue (Python, sbt, scripts, intermediate directories) from the image, and use docker:publishLocal to generate a second single-purpose image that runs only that AnnotateCosmosParquetFiles app.

**Comment by enoriega** [comment]
I'm sold. I think we can abandon this for now.
