### ISSUE TITLE
[code2fn] - Finish .zip -> GrometFNModuleCollection endpoint 

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#231]
We have the base for an endpoint that accepts a source code module as a zip file. We need to update it to support Fortran ingestion and then include it with the rest of the endpoints.

**Comment by myedibleenso** [comment]
@adarshp , are there plans to add similar functionality to the comment extractor (i.e., processing an archive of a directory of arbitrary depth)?

**Comment by adarshp** [comment]
@myedibleenso  - this functionality is implemented for the CLI program [`extract_comments`](https://github.com/ml4ai/skema/blob/main/skema/skema-rs/comment_extraction/src/bin/extract_comments.rs), but not in the REST API.

I can certainly implement it, but I'd like to hold off on it until we decide on whether we're switching to extracting comments as part of the PA pipeline instead of as a separate service (https://github.com/ml4ai/skema/issues/266)

**Comment by adarshp** [comment]
> @myedibleenso - this functionality is implemented for the CLI program [`extract_comments`](https://github.com/ml4ai/skema/blob/main/skema/skema-rs/comment_extraction/src/bin/extract_comments.rs), but not in the REST API.
> 
> I can certainly implement it, but I'd like to hold off on it until we decide on whether we're switching to extracting comments as part of the PA pipeline instead of as a separate service (#266)

Given the urgency for the demo, I went ahead and implemented the functionality (#271)
