### ISSUE TITLE
[code2fn] Single file comment extraction

### ISSUE THREAD

**Issue by jastier** [ml4ai/skema#264]
# Support pre-demo 

- Support comment extraction from a single file 
- Use existing endpoint

## Notes
- Linux only for now

**Comment by myedibleenso** [comment]
We now have a working example in https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/1987984791d74d2cb7bb4698cf91612e111f5b06/end-to-end-rest/notebooks/e2e.ipynb

**Comment by adarshp** [comment]
@myedibleenso  - I suggest just having functions in the example rather than classes - since it looks like the 'docstrings' object is keyed by just the function/method name, ignoring the class within which a method is contained. That is, if you have classes `A` and `B` that both have a method named `method_a`, the docstring for `A.method_a` will be overwritten in the output JSON by the docstring for `B.method_a`, assuming class `B` was defined later in the file than class `A`.

This is one of the known limitations of the comment extractor, but I don't know if it's necessary to fix prior to the open house.

**Comment by myedibleenso** [comment]
@adarshp , thanks for the background on the current version of the comment extractor.  The snippet in the notebook is really more of a placeholder that seemed to demonstrate two types of extracted comments.  If you have an example snippet that you feel would be better, please share!
