### ISSUE TITLE
[code2fn] `/fn_given_filepaths` REST endpoint broken

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#296]
The `/fn_given_filepaths` endpoint no longer works as of https://github.com/ml4ai/skema/pull/288 .

The error seems to relate to the inclusion of the new `comments` attribute of `System` and its default value (see the OpenAPI interactive docs).
```[tasklist]
### Tasks
- [x] check default value for System.comments and inspect its use.
- [ ] https://github.com/ml4ai/skema/issues/298
```

**Comment by vincentraymond-ua** [comment]
@myedibleenso - The fn-given-filepaths endpoint itself is still  working with comments included and excluded. However, there is an issue with the automatically generated example in the interactive docs. This is because the "example" field or the comment definition was accidentally set to an empty string. 

There is actually two issues with this example, the second is it has two files declared in "files" but only one entry in "blob"

I apologize for the confusion, and will correct both of these issues.

**Comment by vincentraymond-ua** [comment]
The first task will be completed with pr #299. Next, I am looking into adding tests to the endpoints.

**Comment by myedibleenso** [comment]
Completed during the hackathon (w/ tests).
