### ISSUE TITLE
[MORAE] - Improve representation of Literal Value

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#402]
Currently :Literal nodes are represented like:
`"value: "ValueL { value_type: "Integer", value: "10", gromet_type: Some("LiteralValue") }"`

This requires extra string manipulation to parse out the value and value_type. Could we instead have Value and Value type as top level fields on the Node?

**Comment by Free-Quarks** [comment]
I think this should be do able!

**Comment by vincentraymond-ua** [comment]
If this hasn't already been worked on in the refactor, this could be a good first issue for me to get hands on with the database code.

**Comment by Free-Quarks** [comment]
I agree! This would get you familiar with the deserialized gromet data struct which is the entry point to a lot of the other code. Since the "value" field in the function_network is not typed rust hates it, so I had to implement a custom deserializer for it, hence the weird structure, but I can walk you through that. It can have a better structure I just wasn't as good at rust back then.

**Comment by vincentraymond-ua** [comment]
## Update 9/19/2023

Starting work on this for the current sprint as an initial task for MORAE database development.

**Comment by vincentraymond-ua** [comment]
## Update 9/22/2023

Improved representation of LiteralValue in Memgraph from the string type above to an Object. When queried from the execution engine, this returns a Dict, which makes accessing individual fields much simpler.


![Image](https://github.com/ml4ai/skema/assets/78653405/c56289bf-077e-437c-9aa6-d055014e01a7)
