### ISSUE TITLE
Automating Model Coverage Analysis

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#577]
Come up with a way to automatically analyze and report, for any model
- How many files we can successfully ingest
- How many files we can't currently ingest
- Report these findings in some kind of tabular form (HTML?) and with some kind of percentage coverage of ingested files
 
Extra ideas
- Error messages describing why we can't ingest files
- Line by line reporting as opposed to per file reporting (using tree-sitter?)
- Idiom tracking (what's covered vs what isn't covered) per language

**Comment by vincentraymond-ua** [comment]
## Update 10/17/2023

Current have initial framework for automatically generating Gromet coverage report. I will post a snippet of the report below, but you can see the full html output at this [Gist](https://gist.github.com/vincentraymond-ua/b1f9e686ca4018c108b2bbd3e1af469d) 


![Image](https://github.com/ml4ai/skema/assets/78653405/e4cbb76e-c891-435b-88c4-bab936861c1f)

I'm working on adding more fields so that we can track things such as how far we can ingest sources (parse with tree-sitter, create CAST, create Gromet).

There are a few known issues:
1. TIE-GCM coverage isn't up-to-date. We need to update the version on the Lum bucket with the included files. 
2. I believe Matlab is generating false positives.

**Comment by vincentraymond-ua** [comment]
## Update 10/20/2023

Added additional fields to track the total number of  support lines in a model and whether or not we can ingest the model as a whole into a single GrometFNModuleCollection

Producing three data products (parse tree, CAST, GROMET) for each file and linking them in table for easy access.

Working on implementing some of the extra ideas posted above such as error and unsupported idiom tracking.
