### ISSUE TITLE
[gromet] Small Gromet Validation (ports)

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#661]
In an effort to determine when Gromet generation we would like to be able to validate certain pieces of Gromet JSON to determine for issues.

For starters, we need to validate wires and their ports. This task is not super complicated and can be doable without having to do a lot of excessive work over the Gromet JSON. This would probably involve checking the src and tgt ports that the wires are referencing.

TODO Justin: We appear to have a utility already to do some validation, where is it and what does it currently do?

**Comment by Free-Quarks** [comment]
The fn_preprocessor is located [here](https://github.com/ml4ai/skema/blob/d5aecfd224b8ea58286be38c5e51f5c9d27b8e26/skema/rest/utils.py#L10-L123)

The current functionality is related to checking fields, such as if there are -1's in the wiring or metadata, if there missing a function_type field, and if there is inline metadata instead of an index.

**Comment by myedibleenso** [comment]
@titomeister , should this have been closed?

**Comment by titomeister** [comment]
Marking as closed due to being solved by issue #697
