### ISSUE TITLE
[ISA] Planning meeting for ISA

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#842]
Getting ISA to a good place for hand-off

**Comment by ualiangzhang** [comment]
Temporarily close this issue since the following evidences are provided. If needed, we can reopen it.

- Added the ISA use case and evaluation [here](https://drive.google.com/drive/folders/16WfF09cfM7kCojMYPQvec2AlYUJSQwG3).
- Added the ISA support documentation [here](https://docs.google.com/document/d/1rhBSkZLtBmPvaXjsNN1iMG8CED8F63kmmvX83YlKl_w/edit?usp=sharing).
- Added the notebook for ISA demo [here](https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/main/end-to-end-rest/notebooks/isa.ipynb).
